
-- Autor: Letícia Ferreira da Silva
      -- Data: 26/10/2021 
 
-- Atividade 1
-- MySQL Script generated by MySQL Workbench
-- Tue Oct 26 13:35:37 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_generation_game_online` DEFAULT CHARACTER SET utf8 ;
USE `db_generation_game_online`;

-- -----------------------------------------------------
-- Table `mydb`.`tb_classe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_generation_game_online`.`tb_classe` (
  `id_classe` BIGINT(50) AUTO_INCREMENT,
  `nome_classe` VARCHAR(20) NOT NULL,
  `habilidade_classe` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id_classe`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tb_personagem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_generation_game_online`.`tb_personagem` (
  `id_personagem` INT AUTO_INCREMENT,
  `fk_id_classe` BIGINT(50) NOT NULL,
  `nome_personageml` VARCHAR(45) NOT NULL,
  `ataque` BIGINT(50) NOT NULL,
  `defesa` BIGINT(50) NOT NULL,
  PRIMARY KEY (`id_personagem`),
  INDEX `fk_id_classe_idx` (`fk_id_classe` ASC) VISIBLE,
  CONSTRAINT `fk_id_classe`
    FOREIGN KEY (`fk_id_classe`)
    REFERENCES `db_generation_game_online`.`tb_classe` (`id_classe`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SELECT * FROM tb_classe;
-- Popule esta tabela classe com até 5 dados.
insert into  tb_classe ( nome_classe, habilidade_classe)
values ("Ninja","facas"),
	   ("lutador","força"),
	   ("guerrero","espada"),
	   ("Bruxa","magia"),
	   ("fada","pirin pin pin");
       
       SELECT * FROM tb_personagem;
       -- Popule esta tabela personagem com até 8 dados.
	
insert into  tb_personagem (fk_id_classe, nome_personageml, ataque, defesa)
values (1,"Rosa",200,900),
	   (1,"flor",200,913),
	   (5,"girasol",1000,900),
	   (1,"couve-flor",2000,1000),
	   (3,"laranja",2030, 1002),
       (4,"abacate",100, 1013),
       (5,"maçã",2024, 200),
       (2,"maçã",2024, 200);
        -- Faça um select que retorne os personagens com o poder de ataque maior do que 2000.
       select * from tb_personagem where ataque >= 2000; 
       -- Faça um select trazendo  os personagens com poder de defesa entre 1000 e 2000.
       select * from tb_personagem where defesa between 1000 and 2000;
       
       -- Faça um select  utilizando LIKE buscando os personagens que tem a letra C
       select * from tb_personagem where nome_personageml like "%c%"; 
       -- c% começa com a letra c, termina com a letra %c
       
       -- Faça um um select com Inner join entre  tabela classe e personagem.
       select * from tb_personagem inner join tb_classe 
        on tb_classe.id_classe = tb_personagem.fk_id_classe;
       -- se não colocar o on ele vai juntar todas as linhas das 2 tabelas
       
	-- Faça um select onde traga todos os personagem de uma classe específica (exemplo todos os personagens que são arqueiros).
       select tb_personagem.nome_personageml, tb_classe.nome_classe 
       from tb_personagem inner join tb_classe
       on  tb_classe.id_classe = tb_personagem.fk_id_classe
       where tb_classe.nome_classe like "%fada%";
       

       

       
       
       



SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

